Remove Android sysroot include and linker paths.
These were unecessary and caused the following compile errors with some setups:

> error: no member named 'XXXX' in the global namespace